version: "3"
services:
   frontend:
       container_name: frontend_con
       build: 
          context: .
       image: frontend
       ports:
          - "3001:3001"
networks:
    default:
       external:
          name: network
